// Unsubscribe link signing for Node senders.
// ------------------------------------------------------------------
// Mirror of src/lib/unsubscribe.ts — the algorithm MUST stay identical so
// links generated by the senders verify against the /api/unsubscribe route.
//   token = HMAC-SHA256(UNSUBSCRIBE_SECRET, lower(trim(email)))  (hex)
import { createHmac } from 'node:crypto'

export function normalizeEmail(email) {
  return (email ?? '').trim().toLowerCase()
}

export function unsubscribeToken(email, secret) {
  if (!secret) throw new Error('UNSUBSCRIBE_SECRET is not set')
  return createHmac('sha256', secret).update(normalizeEmail(email)).digest('hex')
}

export function unsubscribeUrl(email, { appUrl, secret }) {
  const base = (appUrl || '').replace(/\/+$/, '').replace(/^http:/, 'https:')
  const q = `e=${encodeURIComponent(normalizeEmail(email))}&t=${unsubscribeToken(email, secret)}`
  return `${base}/api/unsubscribe?${q}`
}
